spring:
  datasource:
    username: postgres
    password: m@iUoSm-ZjEdmc%Co
  cloud:
    gcp:
      sql:
        database-name: vehicle_report
        instance-connection-name: sbox-ehab-az-db:us-central1:az-mvr-dev

server:
  port: '9000'